### ISSUE TITLE
No description of the last opened project

### ISSUE THREAD

**Issue by binux14** [MosaicManufacturing/canvas-issues#1]
**Describe the bug**
When I open one of my saved projects, the go to the menu where I can see the list of all my projects and I click on the one I had opened before, it doesn't show the details.

**To Reproduce**
1. Open a saved project
2. Click on the menu on the top-left corner
3. Click the project you just opened
4. There should be no details fro that particular project

**Expected behavior**
See the same details as the rest of the projects

**Screenshots**
https://user-images.githubusercontent.com/42580486/44410155-d6c4c380-a531-11e8-9f42-d2b7e8c34531.png

**Operating System (please complete the following information):**
 - OS: Windows 10 (64-bit)
 - Browser Chrome
 - Build 68.0.3440.106

**Additional context**
--

**Comment by mikemklee** [comment]
Thank you @binux14 , this issue has been acknowledged and fixed. The changes will be reflected on the next deployment of CANVAS.
