### ISSUE TITLE
Z height / pause

### ISSUE THREAD

**Issue by awr4sc** [MosaicManufacturing/canvas-issues#101]
When previewing the print, would it be possible to add a z-height notification attached to the sliders on the side. Or if possible, a location to enter pauses?

something like this:

![image](https://user-images.githubusercontent.com/33534561/58767727-e6574b00-854c-11e9-811b-44fb68938864.png)

I often embed objects into the prints and need to see the z-height, and pause the print. 

Thanks,

**Comment by brandonbloch** [comment]
Hello,

We will be adding this (layer height preview with current layer number and Z value) in the next few weeks. Manual pause heights are not currently planned but we will consider the request as well!

**Comment by brandonbloch** [comment]
The layer height sliders in the print preview will now display the layer number and Z height when hovering over the slider. I'm closing this issue as your use case is suitably satisfied, but please feel free to open another issue regarding the request for entering pause heights.

Cheers,
Brandon
