### ISSUE TITLE
Add a "Coast" feature.

### ISSUE THREAD

**Issue by gtjoseph** [MosaicManufacturing/canvas-issues#11]
**Is your feature request related to a problem? Please describe.**
The filaments I print tend to expand in the hotend and don't like to be retracted.  The result are blobs or stringing when the hotend does non-printing moves.

**Describe the solution you'd like**
A Coast feature that would stop extrusion a configuable number of mm instead of doing a retraction.

**Describe alternatives you've considered**

**Additional context**
Similar to Simplify3D's Coast feature.

**Comment by brandonbloch** [comment]
Hi @gtjoseph, thanks for the request!

While there is currently no "coast" setting, CANVAS does have a "wipe" setting, available in the Extrusion section of the style settings. This will either continue moving along a toolpath/loop by that distance, or backtrack along the toolpath/loop by that distance, to perform a similar function. We will keep coasting in mind but I'd be curious to know if using this setting helps you at all in the meantime.

Thanks!
Brandon

**Comment by gtjoseph** [comment]
The problem with wipe is that it's continuing to move over material already extruded for that layer so the material already in the nozzle keeps expanding out and just blobs up.  Let me experiment with more small retraction amounts.  Too much and the material will jam in the hotend.

**Comment by brandonbloch** [comment]
Thank you @gtjoseph, I see the difference in what you're talking about. We will look into adding this functionality!

**Comment by joeynuggetz** [comment]
I think Coast is def needed. I have some filaments that require coast as not matter how much retraction I add the stringing will persist. Coasting is the only known solution. Thanks for considering this.

**Comment by brandonbloch** [comment]
The ability to set a coasting distance for perimeters has landed in CANVAS! You can find the setting in the General tab under Perimeter Seams. As such I'm closing this issue, but feel free to re-open it if you find that you still need the ability to coast on non-perimeter paths after trying it out.
