### ISSUE TITLE
'New Project' opens a blank screen

### ISSUE THREAD

**Issue by Brjodaro** [MosaicManufacturing/canvas-issues#114]
I haven't used Palette before but wanted to test out the slicer. I click "new project" and the window changes to a blank area with "My Projects" at the top center. When I click back or go to menu->projects I get a pop-up in the lower right corner of the screen that says "cannot read property 'dispose' of null". The project that was created appears as a tile, and double-clicking the tile returns me to the same blank screen. (using Chrome)

**Comment by brandonbloch** [comment]
Hi there,

Can you please post a screenshot of the Developer Tools Console (View > Developer > JavaScript Console) when you reach the blank screen? There are likely some error messages in there which will help our investigation.

Cheers,
Brandon
