### ISSUE TITLE
First Layer Height incorrect

### ISSUE THREAD

**Issue by jtkdaddy** [MosaicManufacturing/canvas-issues#117]
In Canvas, set minimum layer height to 0.2 and first layer height to .18.  GCode produced is ignoring first layer height set .

; *** Actual Slicing Settings As Used ***
;
; layer_thickness_mm = 0.2
; max_layer_thickness_mm = 0.2
**; first_layer_thickness_mm = 0.18**
; unsupported_stepover_mm = 0.2
...
; *** Main G-code ***
;
; BEGIN_LAYER_OBJECT z=0.200 z_thickness=0.200
;
; *** Selecting and Warming Extruder 1 to 220 C ***
; Chroma changing to print extruder (T0)
; changing logical extruder to T0
T0
M104 S220 T0
;
;
;
; 'Gap Fill Path', 0.3 [feed mm/s], 16.0 [head mm/s]
G1 X278.444 Y266.546 Z1.45 E0 F4800
G1 X278.444 Y266.546 **Z0.2** E0 F1002
; 'Destring Prime'
G1 E2.2 F1500
; head speed 16.000000, filament speed 0.250116, preload 0.000000
; path_width=0.4000
G1 X278.363 Y266.609 E2.20161 F960
G1 X278.12 Y266.799 E2.20643

Search GCode for G1 .... Z.18 and G1 .... Z0.18 and no matches found.

**Comment by brandonbloch** [comment]
Hi @jtkdaddy,

Thank you for your patience. This bug has been resolved (first layer height was internally forced to always be ≥ the rest of the print's layer height) and your first layer height should now always be respected.

Cheers,
Brandon
