### ISSUE TITLE
Username is case sensitive

### ISSUE THREAD

**Issue by bil-bas** [MosaicManufacturing/canvas-issues#118]
**Describe the bug**
Bilbas != bilbas != BILBAS when logging in
Just found this issue, trying to login on my phone for the first time, where it auto-capitalised my username for me and I couldn't get in! May also affect logging in with an email, but didn't check.

**To Reproduce**
Try to login with a different capitalization of your username

**Expected behavior**
Password should be case-sensitive, but username should not.

**Operating System (please complete the following information):**
Android phone

**Comment by brandonbloch** [comment]
Resolved; login by username and email are now both case-insensitive
