### ISSUE TITLE
Cannot Select Material from dropdown

### ISSUE THREAD

**Issue by JerksonS** [MosaicManufacturing/canvas-issues#119]
On the project creation screen, the material dropdown shows the custom material I entered, but it cannot be selected from the list.
![image](https://user-images.githubusercontent.com/3187941/66232383-aea50f00-e6b6-11e9-8288-eaab11381b00.png)

Browser is Chrome on Win10

**Comment by brandonbloch** [comment]
Hi there,

Apologies about this issue. It's been resolved and the dropdowns are now working correctly. You'll need to refresh the page to see the fix take effect.

Have a great weekend!
Brandon

**Comment by JerksonS** [comment]
I just noticed today it's working. Thanks for being so responsive!
