### ISSUE TITLE
Can't change support settings in "Project settings"

### ISSUE THREAD

**Issue by JerksonS** [MosaicManufacturing/canvas-issues#120]
**Describe the bug**
In a project that is using a printer configured WITHOUT a palette, you cant change teh settings for supports inside "project settings" while you're preparing to slice because you must select an extruder and it seems to be expecting a palette. Upon attempting to save these changes you  receive the error:
![image](https://user-images.githubusercontent.com/3187941/66233268-f0cf5000-e6b8-11e9-984f-f34527d62cc0.png)

**To Reproduce**
1. Create a printer without a palette
2. Begin a project
3. Click settings in the top right of the build plate view
4. Modify supports from medium to light (or vise-versa)
5. Receive error message.
6. re-open settings and confirm your changes to supports did not save.

**Expected behavior**
When no palette is attached to the selected printer, settings to supports shouldnt require a palette id

**Operating System (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 77.0.3865.90

**Comment by brandonbloch** [comment]
Hi there,

Thank you for pointing this out. The issue should now be resolved, and you should see the fix take effect after refreshing the page. Please re-open the issue if you're still experiencing problems with this.

Thanks, and have a great weekend,
Brandon
