### ISSUE TITLE
Feature request: Add layer number comment to GCode

### ISSUE THREAD

**Issue by cscashby** [MosaicManufacturing/canvas-issues#121]
For e.g. DisplayLayerProgress plugin gcode needs to contain ;Layer:x to properly show layer status.

See https://plugins.octoprint.org/plugins/DisplayLayerProgress/ for details.

**Comment by brandonbloch** [comment]
Hi there, this is now possible with the addition of a "layer change" sequence that you can customize for your printer! Something like

```
;Layer:<LAYER>
```

or

```
@printerscript 1.0
";Layer:{{layer}}"
```

can do exactly what you need.

Cheers!
