### ISSUE TITLE
server time out during slicing

### ISSUE THREAD

**Issue by ecobra** [MosaicManufacturing/canvas-issues#129]
I have a model I painted with my step daughter.  I got it to slice a couple time, never on the first try, and then I had to adjust some properties (causing more colors in the lower layers) after the print failed.  I have not been able to get it to slice again.  I test reducing polygon count and I could slice it, but I couldn't replicate the painting on the model with the reduced polygon count.
I am happy to slice it myself on one of my fast computers or pay for some extra server time to get the models going.

**Comment by brandonbloch** [comment]
Hi @ecobra,

I'm sorry to hear you're running into this issue. We noticed a decrease in server performance this past weekend and earlier this week, and believe we have mitigated the issue. As such I'm closing this issue as everything should be ready for you to give it another try, but please do re-open this issue (or reach out to canvas@mosaicmfg.com) if you're still unable to slice without the server timing out. In either case, we'll make sure we can get your print going!

Cheers,
Brandon
