### ISSUE TITLE
[Feature request] Color view by layer height

### ISSUE THREAD

**Issue by joris57** [MosaicManufacturing/canvas-issues#131]
Currently, it is possible to color the sliced model by 'Tool Index', 'Path Type', 'Print Speed', 'Fan Speed' and 'Print Temperature'.

To see the effect of 'variable layer heights' option, it would be nice to be able to also color by 'Layer Height'.

**Comment by brandonbloch** [comment]
Funny you should mention this! We're currently working on some quality and performance improvements to the print preview, and have actually squeezed this feature in (along with bringing back retract/restart points):

![Screen Shot 2019-12-16 at 4 12 08 PM](https://user-images.githubusercontent.com/217964/70943458-f33a1880-201e-11ea-9644-775f522544df.png)

Unfortunately this won't ship until the new year, but as we are planning to release the functionality very soon I'm resolving this issue.

Cheers,
Brandon
