### ISSUE TITLE
Vase mode produces solid infil

### ISSUE THREAD

**Issue by joris57** [MosaicManufacturing/canvas-issues#133]
Vase mode should have a number of bottom layers, but no infill and no top layers. This does not seem to be the case.

**Comment by brandonbloch** [comment]
Was able to reproduce the issue. Should have a bug fix shortly!

**Comment by brandonbloch** [comment]
This fix has now shipped. Apologies for the inconvenience!

![Screen Shot 2020-01-02 at 3 55 29 PM](https://user-images.githubusercontent.com/217964/71692595-54305300-2d78-11ea-952d-94bad4642343.png)
