### ISSUE TITLE
BigBrain3D – Retractable Purge Mechanism for Canvas

### ISSUE THREAD

**Issue by bartofborg** [MosaicManufacturing/canvas-issues#137]
Would like to see Canvas support the purge mechanism by bigbrain. Would save tons of filament!

**Comment by brandonbloch** [comment]
Hi @bartofborg,

Though we don't have a unit to test with, CANVAS should be compatible! CANVAS fully supports side transitioning without any mechanism in a number of ways, and also allows the custom G-code sequences "Before side transitioning" and "After side transitioning". You can edit those sequences when editing your printer, under the Sequences tab. Together, this should provide the needed ability to control movement to and from the mechanism—basically everything in the sequence except the actual purge's extrusion (currently, CANVAS must generate this itself).

Please let us know if that clears things up, or if there's anything we're missing about how the mechanism works that prevents CANVAS from already being compatible!

Cheers,
Brandon
