### ISSUE TITLE
Canvas Crashes When using "Delete" key on keyboard

### ISSUE THREAD

**Issue by jhwblender** [MosaicManufacturing/canvas-issues#139]
**Describe the bug**
When deleting objects if you use the "Delete" key on the keyboard it asks if you want to delete the object and when you click Delete it brings of the "Something went wrong" page and exits the project.

**To Reproduce**
1. Add object onto bed
2. select object
3. click delete key on keyboard
4. click "delete" on dialog box
4. See error "Something went wrong"

**Expected behavior**
The object should delete as it normally does when you click delete on the object browser

**Operating System (please complete the following information):**
 - Windows 10, 64 bit
 - Chrome
 - Version 80.0.3987.122

**Comment by brandonbloch** [comment]
Hi @jhwblender,

Sorry you're running into this issue! I'm unable to reproduce the issue on my end, so I'm wondering if it's something specific to your project/models/etc. Would you be able to share a project + model that causes the crash? This would greatly help us pinpoint the issue. It's also worth hard-refreshing the site to ensure that it's not caching-related.

Cheers,
Brandon
