### ISSUE TITLE
Seam randomization not working

### ISSUE THREAD

**Issue by fluffy-critter** [MosaicManufacturing/canvas-issues#145]
**Describe the bug**

On round models without any corners, the seam always ends up at the specified seam angle regardless of randomization angle

**To Reproduce**

1. Model a round object
2. Set the slicer to maximally randomize the seam angles:
3. Slice the model

**Expected behavior**

Perimeter seams should be evenly distributed around the model

**Screenshots**

Perimeter seam configuration:

<img width="714" alt="image" src="https://user-images.githubusercontent.com/347162/77938500-ab0bd280-726a-11ea-9062-126070272347.png">

Sliced preview with retraction display enabled:

<img width="1585" alt="image" src="https://user-images.githubusercontent.com/347162/77938468-9d564d00-726a-11ea-9732-75aa404bf411.png">

**Operating System (please complete the following information):**
 - OS: macOS 10.15.3
 - Browser: Firefox 74.0

**Additional context**

Model is modeled with multiple solid parts.

**Comment by brandonbloch** [comment]
Hi @fluffy-critter, thank you for the report! I was able to confirm the issue. I believe this is actually related to #146 as well. Would you mind sharing the project here or to canvas@mosaicmfg.com so we can use it as a test case while investigating/fixing the issue?

Thanks,
Brandon

**Comment by fluffy-critter** [comment]
Sure, I'll share both projects with you. Thanks!

**Comment by brandonbloch** [comment]
Thanks for sending! We've found the issue with this setting and are currently testing the fix:

<img width="432" alt="Screen Shot 2020-03-30 at 3 40 25 PM" src="https://user-images.githubusercontent.com/217964/77954836-4158ec00-729d-11ea-8bf0-7ede3743c665.png">

Barring any problems uncovered by further testing, expect this fix sometime tomorrow. I'll close this issue when it's been released.

Cheers,
Brandon

**Comment by fluffy-critter** [comment]
Awesome! Thanks so much.

**Comment by brandonbloch** [comment]
This fix has been released! Let us know if you have any further issues (#146 will remain open as we look for a solution to that separate issue).

Cheers,
Brandon

**Comment by fluffy-critter** [comment]
Hmm, now I'm getting "An unexpected error occurred while slicing." I've tried shift-reloading to make sure there's nothing weirdly cached on the client side, and also removed/readded my project components. Nothing appears in the Javascript console either.

**Comment by brandonbloch** [comment]
Very sorry about that, we had a rare deployment glitch that was causing projects with transition towers to fail during slicing, which only appeared in the production environment (classic). Should be resolved now; please let us know if it's not!

**Comment by fluffy-critter** [comment]
Ah, I know how that goes. :) Slicing seems to be working again and the seams are properly randomized. Thanks!
