### ISSUE TITLE
Unable to change password on the canvas3d.io site.

### ISSUE THREAD

**Issue by cephdon** [MosaicManufacturing/canvas-issues#162]
I logged into the canvas3d.io site. I went to account settings. Clicked on Change Password.
When I attempt to change my password, it appears that the password comparison of the new password is being checked as I type each character. However, once the two passwords match, the validation is not recognizing it. So, you can never actually update the password.

**Expected behavior**
I would have expected the comparison validation to run after the user leaves the password entry (onblur) so that they have finished typing. Or even, run it again when they click save so that they can actually update their password.

**Operating System (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: 83.0.4103.97

**Comment by brandonbloch** [comment]
Hi @cephdon,

Sorry you've been running into this issue! The bug should now be resolved and you should be able to change your password successfully when the fields do match. Please let us know if you still experience any problems!

Cheers,
Brandon
