### ISSUE TITLE
after slicing its showing my project is being printed in one color when it is not

### ISSUE THREAD

**Issue by 8002imas** [MosaicManufacturing/canvas-issues#167]
**Describe the bug**after slicing its showing my project is being printed in one color when it is not

1. Go to new project
2. color parts of the project in 2 colors in my case yellow and white
3.slice the project
4. showing it in one color

I expected it to be shown in Multiple colors like the project

**Operating System (please complete the following information):**
 - OS macOS Catalina 
 - Browser safari 
 - Version 10.15.5

**Comment by mikemklee** [comment]
Could you confirm that your project is using a printer profile that has a Palette attached to it?

Your project will slice in only one color if it does not have an associated Palette.

**Comment by 8002imas** [comment]
I just checked and it did not I when I added it it fixed the problem.
