### ISSUE TITLE
When creating Printer Profile, hitting back goes further back than expected

### ISSUE THREAD

**Issue by brennanfoo** [MosaicManufacturing/canvas-issues#18]
**Describe the bug**
After accidentally selecting Palette+, I wanted to go back and select "I'm not using a Palette." But hitting Back took me all the way back to uploading my slicer profile and entering my print information again.

**To Reproduce**
1. Create a new Project / Printer through the "Upload Slicer Profile" option.
2. Enter printer info, etc. When prompted, select printing with a Palette+
3. On the screen that asks for Loading Offset, etc, hit back. 

**Expected behavior**
Go back 1 screen.

**Screenshots**
https://i.gyazo.com/f64735d60ff2853d87e5cb35c541664e.mp4

**Operating System (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 68.0.3440.106 (Official Build) (64-bit)

**Additional context**

**Comment by mikemklee** [comment]
@brennanfoo Thank you for the issue submission! This issue has been addressed and resolved in the latest version of CANVAS. If you encounter any other issues while using CANVAS, please let us know and we will be happy to respond!
