### ISSUE TITLE
Painted segments can lead to unfused parts

### ISSUE THREAD

**Issue by DataDink** [MosaicManufacturing/canvas-issues#182]
**Describe the bug**
Painting a stripe around an object vertically can lead to a disconnected part. Sometime the gap is big enough to not fuse the part at all. Other times the part is very weakly bonded.

**To Reproduce**
1. Log in to Canvas and open a new multi-material project
2. Import a horizontally oriented cylinder approx 10-20mm diameter 40+mm long
3. Using the paint tool, paint a perfectly straight vertical stripe all the way around the shaft of the cylinder
4. Save / slice
5. --> Observe separation between the painted stripe and the rest of the model.

**Expected behavior**
Some kind of algorithmic protection against model separation
Not sure what the right answer is:
- Infill weaving/interlacing?
- Alternating shell offsets?
- Extra extrusion/blob at the joints?

**Screenshots**
<img width="984" alt="Screen Shot 2020-09-29 at 6 28 09 AM" src="https://user-images.githubusercontent.com/1430521/94565324-e9844900-021d-11eb-81f7-e9d858d7dcf1.png">
<img width="984" alt="Screen Shot 2020-09-29 at 6 13 04 AM" src="https://user-images.githubusercontent.com/1430521/94565358-f739ce80-021d-11eb-8458-97eca4a610d4.png">
<img width="826" alt="Screen Shot 2020-09-29 at 6 12 28 AM" src="https://user-images.githubusercontent.com/1430521/94565365-f99c2880-021d-11eb-98cb-3807285a5c48.png">

**Operating System (please complete the following information):**
 - OS: IOS
 - Browser: Chrome
 - Version: Production as of 9/29/2020

**Comment by brandonbloch** [comment]
Thank you for reporting this, and for the thorough steps to reproduce! This bug has actually been fixed as of a few weeks ago—please let us know and re-open this issue if you're still experiencing any issues with gaps between painted bodies.
