### ISSUE TITLE
Cursors should match the tool icon that is in use

### ISSUE THREAD

**Issue by rcmaniac25** [MosaicManufacturing/canvas-issues#187]
**Is your feature request related to a problem? Please describe.**
When painting, have the facet/circle/fill icons next to the cursor.

**Describe the solution you'd like**
I've had multiple cases where I thought I was in one mode but was actually in another. Usually, thinking I'm in facet mode but was actually in fill more and I end up filling the whole section of the model. The circle mode is generally easy to identify, as there's a circle over the cursor. But facet and fill just show up as a single point, making it annoying to mix up which mode one's in. Having the icon nearby the cursor will make this better.

**Comment by brandonbloch** [comment]
Hi @rcmaniac25, these have now been added as of this morning! Check them out and let us know what you think. And happy painting!

Cheers,
Brandon
