### ISSUE TITLE
Tooltip for Create Region parameters

### ISSUE THREAD

**Issue by rcmaniac25** [MosaicManufacturing/canvas-issues#188]
There are tool tips for nearly every parameter in slice settings and for painting items. But when doing create regions, there are no tool tips and the forums and documentation was replaced with a Q&A system... meaning trying to figure out what each argument is for and how to use it is really just changing them and seeing if they work. Please add tool tips.

**Comment by brandonbloch** [comment]
Thanks for letting us know these were missing—this has now been fixed! You should now be able to see these. Let us know if any of the explanations can be made clearer.

**Comment by rcmaniac25** [comment]
Awesome. The descriptions look good to me at a glance.
