### ISSUE TITLE
Uniform Scale Not Working in Text Fields

### ISSUE THREAD

**Issue by derekVogt** [MosaicManufacturing/canvas-issues#2]
**Description**
Selecting uniform scale and changing a value in  a text field does not update other fields.
 
**To Reproduce**
1. Click 'Uniform Scale' checkbox
2. Enter text into any scale textbox, ie. 10

**Expected behavior**
I would expect other text boxes (and the associated model to update/scale accordingly).

**Operating System (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 68

**Comment by StefanSokic** [comment]
Fixed!
