### ISSUE TITLE
Cannot Import Printer Profile

### ISSUE THREAD

**Issue by BlacMac** [MosaicManufacturing/canvas-issues#218]
**Describe the bug**
Attempted to setup my Prusa i3 Mk2.5 in Canvas. When I uploaded my .ini from Prusa Slic3r, I would get the error: "Cannot read property 'split' of undefined".

**To Reproduce**
1. Go to 'My Setups>My Printers>Import Printer Profile'
2. Click on 'Click or drag here to upload'
3. Scroll down to '[Original Prusa i3 MK2.5 - Copy.txt](https://github.com/MosaicManufacturing/canvas-issues/files/6526845/Original.Prusa.i3.MK2.5.-.Copy.txt) Had to convert from .ini to .txt for upload'

**Expected behavior**
Setup my printer for use. 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/23176952/119234832-c415b980-bae4-11eb-8b65-5c6b54bd587c.JPG)

**Operating System (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Chrome Version 90.0.4430.212

**Additional context**

**Comment by mosaicmradul** [comment]
Hi BlacMac,

Thanks for reporting this issue. 

We’ll take a look on Tuesday after the long weekend in Canada

**Comment by BlacMac** [comment]
<img width="371" alt="Screen Shot 2021-05-25 at 2 15 37 PM" src="https://user-images.githubusercontent.com/23176952/119569520-b15ce800-bd63-11eb-85ce-f91612e0500e.png">
Trying on my Mac and I am getting this error.

**Comment by BlacMac** [comment]
Any update mosaicmradul? Thanks!

**Comment by mosaicmradul** [comment]
Hi BlacMac,

There are several points of failure in the printer profile and it is non-salvageable.

 I am seeing that the profile is 1/4 of the size of a default Prusa i3 Mk2.5 config export.
 
 I think the best course of action here is to try and recreate a new printer profile using the latest [prusa slicer](https://github.com/prusa3d/PrusaSlicer/releases/tag/version_2.3.1) build (2.3.1)

**Comment by BlacMac** [comment]
mosaicmradul,

Thank you for pointing out the size discrepancy. I had no idea the it was different than what was expected. I updated to the latest (2.3.1) and exported my profile with no luck. I did se that we could add a printer model to the list of printers though when I started from scratch. I will try this route for now and will come back with more question if needed. Thank you!
