### ISSUE TITLE
There is no option to paint

### ISSUE THREAD

**Issue by rchamp26** [MosaicManufacturing/canvas-issues#227]
**Describe the bug**

Just logged in and set up a new account in canvas. linked my hub and setup initial printer and profile.

when i import a model in either option (single material or multiple materials) there is no option to paint.

makes buying this piece of hardware useless!

the canvas interface also isn't the same as the video. i only have one color swatch available and not 4

**To Reproduce**
log  into canvas. the app is broken

**Comment by derekVogt** [comment]
Hi rchamp26,

Thanks for reaching out (26 is actually my favorite number!)

When creating your 'Setup', make sure to include your Palette in addition to the Hub in the devices section. 
This will add the additional color swatches and allow the ability to paint when you create a project with that 'setup'.
Your setups can be modified from here: [Canvas - Setups](https://canvas3d.io/setups)

![image](https://user-images.githubusercontent.com/13441469/144899708-6719352d-6552-418f-8db8-3c24217e41d1.png)

Hopefully that fixes your problem! If not feel free to re-open and we can look into this in more detail.
