### ISSUE TITLE
Please stop making us use canvas slicer, its just garbage

### ISSUE THREAD

**Issue by thetechy2** [MosaicManufacturing/canvas-issues#231]
literally cant even just line up the material change with the colored facets in the slicer.

**Comment by derekVogt** [comment]
Closing this issue as the feature request does not meet our standards for detail. Please consider opening an issue that accurately describes your issue. We would appreciate any additional insight you can provide about the functionality you are looking for.

While Canvas might not be the slicer for you, it is powerful (especially with two slicing engines to choose from) and can yield excellent results. If you're more familiar with PrusaSlicer consider looking at [P2PP](https://github.com/tomvandeneede/p2pp) a postprocessing utility that works for Palette 2 and 3. The Palette file formats are not locked down in any way, and allows the community to customize their workflows to their liking.
