### ISSUE TITLE
Add a splice counter in canvas

### ISSUE THREAD

**Issue by xTremePower** [MosaicManufacturing/canvas-issues#245]
Hello,

I love to use the Status en Control windows in canvas to look my Palette 3 print progression,
We can see filament use, % complete, time remaining, ping ...

But strangly, there was no splice counter ! We can't see how many splices left and how many will be in total, only can check this on the Palete screen 

Really strange to not see this :p i think it's as useful as the meters of usef filament 

Thanks 
Zoltan3D

**Comment by brandonbloch** [comment]
Hi Zoltan, thanks for the feature request! This is now available on the Logs tab for Palette 3, above Pings and Pongs.

Cheers,
Brandon
