### ISSUE TITLE
Feature request: Canvas - being able to delete sliced files from Palette

### ISSUE THREAD

**Issue by DivineJimmi** [MosaicManufacturing/canvas-issues#249]
Currently you can only delete sliced files -stored on the palette- on the palette itself. Theres no option yet to select and delete those files from canvas.

**Comment by brandonbloch** [comment]
Hi @DivineJimmi,

It's been a while coming but as of this morning's Canvas update, you can now delete files directly off of Palette 3's internal storage through Canvas. Note that external storage like USB drives must still be managed outside of Canvas.

I hope this improves your experience with Canvas and Palette 3!

Cheers,
Brandon
