### ISSUE TITLE
BUG: mm/s vs mm/min

### ISSUE THREAD

**Issue by theresetmaster** [MosaicManufacturing/canvas-issues#255]
When working with settings on your print profile, speeds are defined as mm/s. When you then in Preview select to show "Print speed" the color coding is presented in mm/min. It would be very nice if the units were the same or that it was possible to select which units to show the speed in.

**Comment by Dandydorf** [comment]
I agree. I had to google the numbers to make sure i wasn’t messing up

**Comment by brandonbloch** [comment]
Hi all, thanks for the suggestion. The print preview now consistently displays print speeds in mm/s.

Cheers,
Brandon
