### ISSUE TITLE
Cannot Save a project name

### ISSUE THREAD

**Issue by wwarwick** [MosaicManufacturing/canvas-issues#26]
**Describe the bug**
When trying to edit and save a project name, I am unable to.

**To Reproduce**
1. Go to Projects
2. Click on any project as though you are going to open it.
3. Click on the "Edit Project icon".
4. Edit the project name.
5. Click on save.

**Expected behavior**
The project name should update to the edited text but does not change from the original.

**Screenshots**
I enter the project name.
![image](https://user-images.githubusercontent.com/39226198/45930924-2123d080-bf34-11e8-8749-c6bd48a3ab90.png)

I click save and get the following result.
![image](https://user-images.githubusercontent.com/39226198/45930945-592b1380-bf34-11e8-9bf0-5db4155a9e3e.png)

**Operating System (please complete the following information):**
 - OS: Windows 10 Professional
 - Browser: Google Chrome
 - Version: 69.0.3497.100 (Official Build) (64-bit)

**Additional context**
None

**Comment by brandonbloch** [comment]
Hi @wwarwick,

Thank you for the report—we have confirmed the issue and will fix it in our next update (early this week). In the meantime, you can edit the project name from within the project:

<img width="1263" alt="screen shot 2018-09-24 at 8 38 07 am" src="https://user-images.githubusercontent.com/217964/45952505-41f03280-bfd5-11e8-9d9e-9df9d1198d69.png">

Cheers,
Brandon

**Comment by brandonbloch** [comment]
We have fixed this issue in our latest update. I'm closing this as fixed; if the problem persists, feel free to re-open it.

Thanks,
Brandon
