### ISSUE TITLE
Internal server error (258)

### ISSUE THREAD

**Issue by BillC58** [MosaicManufacturing/canvas-issues#265]
**Describe the bug**
Error is received on slicing project. It occurs on numerous projects. I have not checked them all.

**To Reproduce**

1. Click on Slice

**Expected behavior**
Slicing to occur

**Screenshots**
See file

**Operating System (please complete the following information):**
Windows 11, Edge browser

**Additional context**
None
![2023-04-14_08-34-29](https://user-images.githubusercontent.com/60044767/232089919-ec7b522f-0481-4c02-b13b-1b31d75c8388.png)

**Comment by brandonbloch** [comment]
Hi there, thanks for reporting this! The issue affected the slicing of projects using KISSlicer and has now been resolved. Please let us know if you're still experiencing any issues.

Cheers,
Brandon
