### ISSUE TITLE
Link to "Open-source licenses" points to a 404

### ISSUE THREAD

**Issue by robzach** [MosaicManufacturing/canvas-issues#268]
**Describe the bug**
The link to read the license text for all the open-source projects included in Canvas points to a 404.

**To Reproduce**
Click "Open-source licenses" in the lower left of Canvas (I'm accessing it at CMU so the URL mine points to is `https://array.ideate.cmu.edu/licenses.txt`)

**Operating System (please complete the following information):**
 - OS: OSX 13.5
 - Browser: Chrome
 - Version: 116.0.5845.140

**Comment by brandonbloch** [comment]
Hi @robzach, thanks for reporting! The link should actually be https://canvas3d.io/licenses.txt – we should have this fixed shortly.

Thanks,
Brandon

**Comment by brandonbloch** [comment]
Hi @robzach, this should now be fixed. Thanks again for letting us know.

Happy printing!
Brandon
