### ISSUE TITLE
Unable to Save New Printer

### ISSUE THREAD

**Issue by Setesh82** [MosaicManufacturing/canvas-issues#27]
When trying to add a new printer an "undefined" error occurs.

**Steps:**
- Add Printer
- Name printer
- Update printer properties
- Save

![canvaserror](https://user-images.githubusercontent.com/25417902/45963117-702f3b80-bff0-11e8-95f6-2f11791e9b62.JPG)

**Comment by brandonbloch** [comment]
Hi @Setesh82,

Sorry about this! We have just released an update that should address this issue. Please give it another try and let us know if you're still having trouble! If the update fixes it, please feel free to close this issue.

Thanks,
Brandon

**Comment by Setesh82** [comment]
Issue has been resolved.

**Comment by brandonbloch** [comment]
Glad to hear!
