### ISSUE TITLE
support deletion is laggy

### ISSUE THREAD

**Issue by touretzkyds** [MosaicManufacturing/canvas-issues#270]
**Describe the bug**
When editing custom supports, if you do "Toggle preview" to see the vertical lines where support will go, then deleting supports becomes laggy. This is very confusing for users who click and drag on an area and nothing happens. So they try clicking and dragging again, and eventually some things disappear. Only a second or two of lag is enough to totally disrupt people's experience.

**To Reproduce**
1. Access the portal using Google Chrome; I haven't tried this on other browsers.
2. Load a model with large overhangs.
3. Auto-generate supports for it.
4. Go to "Custom supports", do "Toggle preview".  There should be a good amount of support visible.
5. Set the paintbrush to "Off" mode and try deleting some support. Observe the lag.

**Expected behavior**
Deleting supports should be instantaneous. There should not be any noticeable lag. If there is lag, your algorithms need improvement.

**Operating System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Chrome
 - Version 114.0.5735.90 (Official Build) (64-bit)

**Comment by brandonbloch** [comment]
Hi @touretzkyds,

We've made some performance improvements to custom support painting, including visual improvements to the preview structure and improvements to real-time updating of the preview while painting. Hopefully this alleviates some of the issues you've been experiencing; please feel free to comment here if you're still experiencing any issues.

Cheers,
Brandon
