### ISSUE TITLE
Slic3r leading zero missing in Z movement

### ISSUE THREAD

**Issue by moberli** [MosaicManufacturing/canvas-issues#274]
**Describe the bug**
If you use Slic3r instead of KISSlicer - the files contain a Z movement without leading Zero example:
G1 Z.8 F3000 ; lift Z

It will be glad if there is a possibility to activate the Regex function to allow leading zero's 

**To Reproduce**
1. Slice a Object with Slic3r and see the G1 Z movement.

**Expected behavior**
It will be glad if in the option is possible to activate leading Zero's with the solution Prusa had added to theirs Slic3r.

**Additional context**
https://github.com/prusa3d/PrusaSlicer/issues/6996

**Comment by brandonbloch** [comment]
Hi @moberli,

Thanks for linking to that issue! We've added a postprocessing step that should restore leading zeros as needed, so this should now be addressed and working as you'd expect. If you're still running into any issues, please feel free to comment on this thread or re-open the issue.

Cheers,
Brandon

**Comment by moberli** [comment]
Great Job - Thank you!
