### ISSUE TITLE
Creating Regions On Detailed STL Files Doesn't Work

### ISSUE THREAD

**Issue by ADYoungberg** [MosaicManufacturing/canvas-issues#275]
**Describe the bug**
Trying to create regions on a detailed STLs will not work. Clicking on the button "Create Regions" pops up a message indicating it may take time to complete due to the size. Clicking "Save" will save the progress, then the message box returns. Clicking "Don't Save and Continue" does nothing. Appears the button is broken.

**To Reproduce**
1. Go to 'Paint'
2. Click on 'Create Regions'
3. Click on 'Continue Without Saving'
4. Button does not create regions

**Expected behavior**
There should be a loading or "Creating Regions" message. Regions should be created.

**Screenshots**
![Screenshot 2024-01-01 132426](https://github.com/MosaicManufacturing/canvas-issues/assets/36788667/c1179fd1-dec8-40e7-9045-90665c955d7c)

**Operating System (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome or Edge
 - Version Chrome: Version 120.0.6099.130 (Official Build) (64-bit)

**Comment by brandonbloch** [comment]
Hi @ADYoungberg, thanks for reporting this issue. This should now be resolved and working correctly; we apologize for the inconvenience. Please let us know if you're still experiencing any issues.

Thanks,
Brandon
