### ISSUE TITLE
Style Profile - Copy / Share

### ISSUE THREAD

**Issue by Setesh82** [MosaicManufacturing/canvas-issues#28]
It would be nice to have the option to start a style profile from an already existing style.  You kind of get this with importing from another slicer but nothing for Canvas styles.

Additionally being able to share or export style profiles.

**Comment by mikemklee** [comment]
@Setesh82 Thank you for your request! This feature is now implemented in CANVAS. When you try to create new styles, you will now be given a 3rd option that allows you to create style profiles by copying from your existing profiles. Please feel free to post any other issues that you encounter while using CANVAS! We will be happy to respond.
