### ISSUE TITLE
Crash when trying to edit splice settings

### ISSUE THREAD

**Issue by dgrant** [MosaicManufacturing/canvas-issues#282]
**Describe the bug**

Go to 

**To Reproduce**
1. Go to https://canvas3d.io/materials
2. Click on "Splice Settings"
3. Choose Device Type
4. Choose materials
5. Try to type anything in the Heat, Compression, or Cooling text boxes.
6. The app crashes

**Expected behavior**
Expected no crash

**Screenshots**

![image](https://github.com/user-attachments/assets/095e7d52-a7c9-4ab4-9d2c-792b1d37dce6)

**Operating System (please complete the following information):**
 - OS: Ubuntu 24
 - Browser Chrome
 - Version 131.0.6778.69

**Additional context**

**Comment by brandonbloch** [comment]
Hi @dgrant,

Sorry you're running into this issue. There's a known bug with splice settings that will be fixed shortly in an upcoming release which causes a crash when selecting the first material in the list, which is named "Generic", but isn't actually a material profile that can have splice settings associated. If you select Generic for either the ingoing or outgoing material (or both), changing any values will cause a crash:

<img width="442" alt="Screenshot 2024-11-18 at 10 10 52 AM" src="https://github.com/user-attachments/assets/4a37d80c-37a4-4b6c-97e3-815ab8ef8a21">

Is this the issue you're running into? Or do you see a crash when neither of the selected profiles is this "Generic" option? Please let us know; we're not aware of any issues when using regular material profiles, so if there is another problem we'll look to fix it ASAP.

Thanks,
Brandon

**Comment by dgrant** [comment]
@brandonbloch thanks, that was the issue! So I created a new PLA material and that is able to have splice settings with my soluble material.

**Comment by brandonbloch** [comment]
@dgrant glad to hear it! The erroneous Generic option will be removed in our next update and this issue should not be able to occur anymore once that goes live.
