### ISSUE TITLE
Transition tower located in the middle of the bed

### ISSUE THREAD

**Issue by HangarZero** [MosaicManufacturing/canvas-issues#32]
Hi all.
I'm having some issues with Canvas when generate the gcode.
The transition tower is allways in the middle of the bed….maybe I'm doing something wrong, but...I've tried several times and same result ever

![image](https://user-images.githubusercontent.com/43811675/46405662-2ee20e80-c709-11e8-8288-44af47cb8abc.png)
Best regads

**Comment by HangarZero** [comment]
...just find how to move the tower...but still an issue.
The "tool" to select the transition tower doesn't appears in google chrome in my laptop (17" screen).
Something related with resolution?. 

And...if it's not optimized for Chrome...see last pic...Microsoft explorer.

I still consider this as a bug...;)

![image](https://user-images.githubusercontent.com/43811675/46406283-4e7a3680-c70b-11e8-8c70-ac47617aef6d.png)
![image](https://user-images.githubusercontent.com/43811675/46406399-b16bcd80-c70b-11e8-93c6-a70141f17e95.png)
![image](https://user-images.githubusercontent.com/43811675/46406484-fbed4a00-c70b-11e8-88cd-737de9df3638.png)

Best regards.

**Comment by brandonbloch** [comment]
Hi @HangarZero,

We are aware of the auto-positioning of the transition tower being incorrect and are working on adding smarter auto-positioning logic that is still faster than the full auto-arrangement. We'll update this issue as this work progresses.

I'd just like to confirm, does the transition tower preview appear in this location even though it overlaps with the print? The tower being non-representative of the final position would be a different issue altogether, one we have not seen.

We will be releasing an update today that reduces the vertical size of the model manipulation tools, which should prevent the auto-arrange button being too low. Please also note that you can use the Move tool to manually position the transition tower, as well as the Scale tool to adjust its size!

Lastly, CANVAS does not currently support Internet Explorer—we do fully support Chrome, Firefox, Safari, and Microsoft Edge, so I would recommend using Edge over IE when using CANVAS.

Cheers,
Brandon

**Comment by brandonbloch** [comment]
This issue has been addressed and considered fixed as of yesterday. If there are still problems with the new approach, feel free to re-open this issue!
