### ISSUE TITLE
Skirts ignore supports and neighboring parts

### ISSUE THREAD

**Issue by wwarwick** [MosaicManufacturing/canvas-issues#34]
When printing with a skirt and supports, the skirt prints by being offset from the first part layer that is on the print bed even if that means overlapping with supports. Also, if the skirt from one part would overlap the skirt from a neighboring part, the skirt does not adjust to avoid printing over top of one another.

1. Print a part with an external overhang requiring support where the overhang is greater than the skirt offset value.
2. you will see that the skirt overlaps the supports.
3. Print 2 parts on the print bed and create a skirt with enough outlines that there is not enough room for all of them between the two parts.
4. You will see that rather than adjusting, the skirts will overlap.

**Expected behavior**
I would expect that the skirt would be offset from all printing on the print bed.

**Operating System (please complete the following information):**
 - OS: Windows 10 Professional
 - Browser: Chrome
 - Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by brandonbloch** [comment]
Hi @wwarwick, this issue has been addressed as of yesterday. Brims/skirts and rafts of neighbouring parts should now correctly union (join into one) rather than produce overlapping toolpaths.

If you still experience problems with this, feel free to comment or reopen.
