### ISSUE TITLE
can create profile

### ISSUE THREAD

**Issue by Elenedeath** [MosaicManufacturing/canvas-issues#38]
Hello,
when you want to add a printer
select 'add new' after 'create profile' and try to save.
got this error "Parameter 'gpxProfile' is required but was not provided"

i try to change settings or import an S3D profile, doing the same.
always the same error

[http://prntscr.com/lay93w](http://prntscr.com/lay93w)

 - OS: Windows 10 Pro 64bits
 - Browser: chrome
 - Version:  70.0.3538.77 (Build officiel) (64 bits)

**Comment by DanielGuns** [comment]
Hello,

Also I have the same problem, I try to add multiple profiles and all have the same error ..

**Comment by Elenedeath** [comment]
error resolved, i try and working now

**Comment by brandonbloch** [comment]
Hi all,

Sorry you ran into this issue! We have put out an update today that should prevent this issue. Please do let us know if you're still experiencing this problem.
