### ISSUE TITLE
Upload Printer Profile not working in Firefox

### ISSUE THREAD

**Issue by brandonbloch** [MosaicManufacturing/canvas-issues#4]
**Describe the bug**
The control to upload the profile is nonfunctional in Firefox. You can't get as far as even selecting the profile to load.

**To Reproduce**
1. Use Firefox
2. Attempt to upload a profile

**Expected behavior**
File selector should appear

**Operating System (please complete the following information):**
 - Browser: Firefox

**Comment by brandonbloch** [comment]
See https://support.mosaicmanufacturing.com/hc/en-us/community/posts/360015295253-Upload-Printer-Profile-not-working-in-Firefox?flash_digest=71c4d2f2584d15506311549acc027ae7bd25bc91 for original report

**Comment by ShadMan5** [comment]
It also did not work when accessing through MS Edge.

**Comment by mikemklee** [comment]
Thank you @brandonbloch @ShadMan5 , this issue has been acknowledged and fixed. The changes will be reflected on the next deployment of CANVAS.
