### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by steve220** [MosaicManufacturing/canvas-issues#46]
**Describe the bug**
When rotating a model, I get an "Internal Server Error"

**To Reproduce**
1. Place model
2. Click on Rotate
3. Try rotating the model

**Expected behavior**
Model rotates without an Error

**Screenshots**
![canvaserror01](https://user-images.githubusercontent.com/38285868/48913861-ec020480-ee36-11e8-89e0-8ac8db95445a.jpg)

**Operating System (please complete the following information):**
 - OS: Win 7
 - Browser Chrome - Version 70.0.3538.110 (Official Build) (64-bit)

**Additional context**

**Comment by brandonbloch** [comment]
Hi @steve220,

Thanks for reporting this! We discovered this issue today and will be rolling out the fix this afternoon. I’ll follow up when the rollout is complete.

Cheers,
Brandon

**Comment by brandonbloch** [comment]
Following up to let you know this update has been rolled out. Thank you for your patience!

I'll close the issue but if you do still run into problems please feel free to re-open it.

Cheers,
Brandon
