### ISSUE TITLE
Clicking Reset in the Move Dialog throws error

### ISSUE THREAD

**Issue by steve220** [MosaicManufacturing/canvas-issues#47]
**Describe the bug**
Clicking Reset in the Move Dialog throws error

**To Reproduce**
1. Go to 'move'
2. Click on 'reset'
3. See error

**Expected behavior**
STL moves to default position

**Screenshots**
![canvaserror02](https://user-images.githubusercontent.com/38285868/48957480-0068fe80-ef16-11e8-8176-dc9ed8d98f4a.jpg)

**Operating System (please complete the following information):**

**Additional context**

**Comment by brandonbloch** [comment]
Thanks for the report! This afternoon's update should resolve this issue.

Cheers,
Brandon
