### ISSUE TITLE
Colour selection, Object box

### ISSUE THREAD

**Issue by nxt-dimension** [MosaicManufacturing/canvas-issues#51]
**Is your feature request related to a problem? Please describe.**
Whilst in the colour selection step the only way to pick your colours is to drag and drop, either directly onto the model or into the object browser.
>>The object browser is not big enough to see all objects unless you scroll. The object browser can not be enlarged by clicking and dragging on a corner.

**Describe the solution you'd like**
I would like to be able to click parts of the model directly (and/or objects in browser) and highlight them (holding ctrl for multiple objects), and then select my colour for the highlighted objects. This would be very useful for multiple or small parts that are in the model instead of trying to drag and drop a colour onto all of the individual objects. This would be extremely handy for a print with a lot of small parts so you don't have to zoom in to the part specifically and select colour, or look for the part in the object browser.
>> I would like to see the object browser grow with the number of objects so as many as possible are visible. Object browser box should have handles to click and drag to an alternative size.

**Describe alternatives you've considered**
 Objects can be grouped and coloured by group, but this would mean breaking apart the original group to select smaller parts inside a larger group. Directly clicking objects seems like a faster way to achieve the desired outcome.

**Comment by brandonbloch** [comment]
You can now drag-and-drop a color onto the Objects list and it will be applied to all selected models.
