### ISSUE TITLE
Purge to infill/support

### ISSUE THREAD

**Issue by xile6** [MosaicManufacturing/canvas-issues#52]
Is it possible to add purging to support.

**Comment by brandonbloch** [comment]
Hi @xile6,

Chroma has this functionality but it has not yet been implemented in CANVAS. However, implementation is planned (along with purging in infill) and should be expected early next year.

**Comment by brandonbloch** [comment]
Purging to infill is now available! The option can be found in the Transition section of your style settings.

Purging to support is somewhat more complicated, as the implementation of that feature depends on changes required for #79. Keep an eye on that issue for updates regarding support transitioning as well.
