### ISSUE TITLE
Colour names reported incorrectly

### ISSUE THREAD

**Issue by bil-bas** [MosaicManufacturing/canvas-issues#53]
**Describe the bug**
Colour names not sensible in some cases

**To Reproduce**
Setting colour to #303030 or #404040 is described as Dark Brown! #444444 and #505050 show as Dark Grey, as I'd expect. #202020 shows as Black

**Expected behavior**
#303030 and #404040 should be Dark Grey.

**Operating System (please complete the following information):**
 - OS:Android
 - Browser chrome
 - Version Beta (today)

**Comment by binux14** [comment]
To add to this, if you go to the color settings and click on the blue rectangle on top, the result is clearly blue but it says "Purple":
![purple](https://user-images.githubusercontent.com/42580486/49813634-da28c880-fd35-11e8-9611-f4e37924e8df.png)

**Comment by brandonbloch** [comment]
Thanks for letting us know! Our latest update (just released) improves the color auto-naming functionality and should cover many more of these edge cases. Please feel free to re-open if you notice that some color names are still incorrect or inconsistent.

Cheers,
Brandon
