### ISSUE TITLE
Cannot update canvas plugin

### ISSUE THREAD

**Issue by rjlorimor** [MosaicManufacturing/canvas-issues#55]
I'm unable to update the canvas plugin on a new canvas hub from 0.1.0 to 0.8.0. It gives me an error, "Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/home/pi/OctoPrint/venv/lib/python2.7/site-packages/Canvas-0.1.0-py2.7.egg-info/requires.txt'
Consider using the `--user` option or check the permissions."
I'm attaching logs
[plugin_softwareupdate_console.log](https://github.com/MosaicManufacturing/canvas-issues/files/2660613/plugin_softwareupdate_console.log)
[octoprint.log](https://github.com/MosaicManufacturing/canvas-issues/files/2660614/octoprint.log)

**Comment by brandonbloch** [comment]
Hi @rjlorimor,

CANVAS Hub issues are tracked separately and should instead be directed to the plugin repository (for the CANVAS plugin, https://gitlab.com/mosaic-mfg/canvas-plugin). Sorry about the confusion; I will update the readme on this repo's homepage to indicate this.
