### ISSUE TITLE
Feature Request: Explicit retraction location

### ISSUE THREAD

**Issue by jmsjgill** [MosaicManufacturing/canvas-issues#58]
Simplyfy3D (version 4.x and up) allows for explicit control of retraction locations.  For example, they can be explicitly random, optimized for the build, or always closest to a specific point in X,Y.  This is extremely useful for hiding "Z seams" and other retraction artifacts in specific details of a printed model.

Please add this ability to CANVAS, as it is one of the things that prevents me from using it regularly.

Alternately, consider adding a method to import *.gcode from S3d into CANVAS for Palette processing in order to preserve these controls.

**Comment by brandonbloch** [comment]
This functionality is live in CANVAS as of yesterday! You can find the relevant settings in the General tab, under Perimeter Seams.
