### ISSUE TITLE
Wrong temperature

### ISSUE THREAD

**Issue by clearbucketLabs** [MosaicManufacturing/canvas-issues#59]
**Describe the bug**
Set temperature for PETG profile to 250 first layer, 255 after.   But uses 170c on start of print.

**To Reproduce**
1. Load keychain
2. setup a profile for PETG (0,0,-3) splice setting.  Set 0.3 layers, 250 temp first layer, 255 every other. 
3. Slice
4. Download for Canvas Hub
5. Upload to hub
6. Start Print
7. Print starts calibration routine (MK2.5)
8. Stops to wait for heat up, but instead of 250, it's doing 170c....

Printer: Prusa MK2.5 -  Canvas + Hub (manual upload since it wasn't connected... apparently)

**Comment by brandonbloch** [comment]
Hi @clearbucketLabs,

Sorry about this issue! Do you happen to know where the 170 came from? As far as I know this isn't a default temperature. I just want to clarify that this material profile was used for each of the inputs where you're using PETG. If no material is set for an input, it uses default splice settings (0, 0, 0) and the project-wide style settings (including temperature) for that input.

Would you mind opening the project, downloading the help package (right-hand menu > Get Help with CANVAS > Download help package), and sending that to canvas@mosaicmfg.com so we can take a look at what's happening?
