### ISSUE TITLE
Palette 2 Plugin and Palette 2 Device Statistics Report Mismatch

### ISSUE THREAD

**Issue by rsvp95** [MosaicManufacturing/canvas-issues#60]
Describe the bug
46% into the print Plug in reports "Latest Pong: Pong 1  100%" whereas Device reports 11 Pongs

To Reproduce
Run and Calibration print and watch the plugin and device statistics reports

Expected behavior
Statistics reports in plugin should match the device

Screenshots
Attached, please find.

Operating System (please complete the following information):

OS: Windows 10 Pro
Browser Chrome
Version 71.0.3578.98 (Official Build) (64-bit)
[statisticsreportspictures.zip](https://github.com/MosaicManufacturing/canvas-issues/files/2705268/statisticsreportspictures.zip)

**Comment by rsvp95** [comment]
Describe the bug
46% into the print Plug in reports "Latest Pong: Pong 1  100%" whereas Device reports 11 Pongs

To Reproduce
Run and Calibration print and watch the plugin and device statistics reports

Expected behavior
Statistics reports in plugin should match the device

Screenshots
Attached, please find.

Operating System (please complete the following information):

OS: Windows 10 Pro
Browser Chrome
Version 71.0.3578.98 (Official Build) (64-bit)
[statisticsreportspictures.zip](https://github.com/MosaicManufacturing/canvas-issues/files/2705268/statisticsreportspictures.zip)

**Comment by brandonbloch** [comment]
Hi @rsvp95,

Thank you for the report! However, CANVAS Hub issues are managed separately on the respective plugin repositories. Please open this issue on the Palette 2 Plugin issue tracker: https://gitlab.com/mosaic-mfg/palette-2-plugin

Cheers,
Brandon
