### ISSUE TITLE
Canvas Side Transition X & Y Coordinates do not do not work/stick

### ISSUE THREAD

**Issue by wmmc01** [MosaicManufacturing/canvas-issues#66]
**Describe the bug**
CANVAS: Entering the X & Y Coordinates for Side Transitions does not work, or take effect. As you progress through the rest of the settings, the result is always printing a purge line at the back of the print bed, instead of a purge position at X & Y specific location. 

**To Reproduce**
1. Go to 'New Project'
2. Click on 'Printer
3. "Edit Printer Profile
4. Check "Transition in Place"
5. Enter X & Y coordinates
6. Click Save
7. Edit the material profile - and you will see you cannot change any setting for a specific coordinate on the settings. 
8. Finally, import your model, slice & preview - you will see that you will get a purge LINE, as opposed to purging at a coordinate location.
9. If you go back into the printer profile, you will see that the X & Y coordinates are blank, in spite of "Saving". 

**Expected behavior**
You should be able to purge at specific X & Y coordinates in a N, S, E, W direction of the bed. 

**Screenshots**

**Operating System (please complete the following information):**
 - OS: Win10 Pro 64
 - Browser Chrome,
 - Version: Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Additional context**

**Comment by brandonbloch** [comment]
Hi @wmmc01,

Sorry about this! The issue should now be resolved with our most recent update. Please try again and feel free to re-open this issue if there's still a problem.

Cheers,
Brandon
