### ISSUE TITLE
Feature Request: Allow Target Positions below 20%.

### ISSUE THREAD

**Issue by brennanfoo** [MosaicManufacturing/canvas-issues#68]
Owner of www.sublimelayers.com is requesting the ability to drop Target Position below 20%.

"I'm doing 20% and would love to go down to 10%! I think my system can handle it."

**Comment by brandonbloch** [comment]
Done. When going this low, please keep in mind the risks (i.e. higher chance that going slightly off calibration in the early direction results in color bleed).
