### ISSUE TITLE
Error Screen on Preview Every time a Setting is Changed

### ISSUE THREAD

**Issue by cleetose** [MosaicManufacturing/canvas-issues#69]
**Describe the bug**
Every time I change a print setting and go to the Preview screen to slice, I am greeted with the "Oops..! Something went wrong!" error screen. After reloading and reopening the project, I don't get the error on the preview screen, unless I change another print setting.

**To Reproduce**
1. Open or create a Project.
2. Click on the Settings tab.
3. Change any setting
4. Go to Preview tab.
5. See Error

**Expected behavior**
I expect to not see the error screen every time I Preview after changing a setting.

**Operating System (please complete the following information):**
 - OS: Windows 10
 - Browser: I tested and saw the same error in Chrome and Edge
 - Version- 71.0.3578.98 (Chrome), 44.17763.1.0 (Edge)

**Comment by brandonbloch** [comment]
Hi @cleetose,

Thanks for the report! This issue was caused by Friday's update but has now been resolved.

Cheers,
Brandon
