### ISSUE TITLE
Missing Retraction/Returns

### ISSUE THREAD

**Issue by cleetose** [MosaicManufacturing/canvas-issues#70]
**Describe the bug**
This issue seems to be related to the transition tower in some way. Sometimes during a print, when moving from the model to the transition tower, the printer does not retract, but it does the return move resulting in a large blob at the start of the perimeter. And then, when it next goes to the model, the printer retracts, but it does not return, resulting in a gap in the print.

I opened the G-Code files in Simplify3D so I could see if it was a printer issue, or a slicing issue. When I got to the affected part of the model I could see the missing retraction and return, so I believe the problem is with the slicer and not my printer.

**To Reproduce**
 I haven't been able to work out any consistent reproduction, but I am seeing it in a large number of files. It appears to only happen in layers where there are no transitions.

**Expected behavior**
A retraction before every travel move, followed by a return before starting a new perimeter (unless overridden by the reaction threshold).

**Screenshots**
Here's the view in Simplify3D showing the missing retraction:
![no_retract](https://user-images.githubusercontent.com/46411258/50732286-bdad5f80-112c-11e9-94a7-525b2c4d8e46.png)

And here's the view showing the missing return:
![no_return](https://user-images.githubusercontent.com/46411258/50732287-c00fb980-112c-11e9-9a11-6b0726c2a027.png)

Here's a shot of a two colored key ring. You can see the two blobs on the tower, and the corresponding extrusion gaps in the key ring.
![20190105_213152](https://user-images.githubusercontent.com/46411258/50732526-91481200-1131-11e9-9cc1-cf5264ec840f.jpg)

**Operating System (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version:  71.0.3578.98

**Comment by brandonbloch** [comment]
Hi @cleetose,

Sorry you're experiencing this issue. Would you be able to send your GCode file to canvas@mosaicmfg.com so we can take a closer look?
