### ISSUE TITLE
Cooling fan does not turn on after first layer, Prusa MK2

### ISSUE THREAD

**Issue by JohnYip36** [MosaicManufacturing/canvas-issues#73]
I'm running a Palette 2 using Canvas to slice.  Using canvas hub with Prusa MK2.  Once file is sliced and sent to the printer, it seems all is fine but cooling fan never turns on.  

**To Reproduce**
Just slice any file and use Prusa MK2 printer profile and send it through to the Canvas hub.  

**Expected behavior**
Part cooling fan will not turn on after first layer.  

**Screenshots**

**Operating System (please complete the following information):**
Canvas with Canvas hub

**Additional context**

**Comment by brandonbloch** [comment]
Hi @JohnYip36,

Thank you for opening this issue. This is a known bug at the moment but it appears we didn't have an issue here yet. Fortunately, there are some workarounds in the meantime:

- the issue does not seem to occur for single-color prints
- disabling "Use PWM with fan" in your printer's machine settings (on the Advanced Settings screen) should resolve the issue

If neither of those are the case please let us know! It will greatly help us narrow down why the issue occurs.

Cheers,
Brandon

**Comment by brandonbloch** [comment]
This issue should be resolved by now. Please let us know/re-open the issue if this error is still occurring!
