### ISSUE TITLE
Support is current filament

### ISSUE THREAD

**Issue by mylife4aiurr** [MosaicManufacturing/canvas-issues#79]
![Imgur Image](https://i.imgur.com/PORZvdV.jpg)
Currently supports are tied to a specific extruder. So for instance a 4 color print. User must assign an extruder for support. If the user chooses support extruder as 3. Then every color that isnt extruder 3 needs a splice created and then extra time and material wasted to get back to extruder 3's to do the actual support. So an extra splice and extra time is needed to transition fully back to the support extruder.
![Imgur Image](https://i.imgur.com/qCZ2o6G.jpg)
Why not make the support extruder the current color. Now a new splice isn't necessary, which also saves time because a full transition isn't necessary. 
Of course this would not apply for filaments like PVA supports or interface support only, in this case you want a specific extruder for support only. This request is only same material as support.

edit: grammer

**Comment by brandonbloch** [comment]
Thank you for this request! This is definitely the ideal situation (and the same would apply to rafts and skirts/brims) and is planned in the medium-term. The default option would basically be "auto" with the ability to force a specific extruder as is the current behaviour, for printing with solubles.

**Comment by mylife4aiurr** [comment]
Ok thanks 4 acknowledgement. just looking to save time and splices

**Comment by mylife4aiurr** [comment]
Hey brandon, 
some1 else just asked a very similar question on the facebook group..... its been 7months, any update?
https://www.facebook.com/groups/mosaic.users/permalink/391412704828637/

**Comment by brandonbloch** [comment]
Hi all,

I know it's been a while since this was requested, but this feature is now here with the option to select "Auto" for the support extruder. This will make sure to re-use an extruder on that layer, so as to not add a transition. This does not affect interface layers if enabled.

Cheers,
Brandon

**Comment by mylife4aiurr** [comment]
Thank you for your work Sir 👍
