### ISSUE TITLE
Side transition (transition in place) purging speed= infill speed

### ISSUE THREAD

**Issue by AngelCrusher** [MosaicManufacturing/canvas-issues#80]
**Describe the bug**
When purging side transition (in place) purge speed goes too fast (sets side transition purge speed to what your infill speed is set to)

**To Reproduce**
Slice in canvas with - side transition on, transition in place (transition speed 1mm/s) = gcode :
M104 S220 T0
; Chroma toolchange handling
; toolchange at totalE = 1215.23814
; changing logical extruder from T1 to T3
G1 X267 Y330 F8520 ; move to side
G1 E45.73319 F1800 ; destring prime
G1 F3000
G1 E175.73318 F3000
G1 E175.03319 F1800 ; destring suck
; leave side
; Reset extruder pos
G92 E0
; endchroma

**Expected behavior**
Purge speed would be preformed at 1mm/s not F3000

**Operating System (please complete the following information):**
W10, Chrome latest, connected mode P2 PRO

--feedrate looks appropriate when using plain side purge (N,S,E,W)

**Comment by brandonbloch** [comment]
Feedrate should actually be `60` (mm/min) rather than `1` but that's besides the point. We will investigate; thanks for pointing this out!

**Comment by brandonbloch** [comment]
Hi again,

The issue has been fixed and the update is now live.

Cheers,
Brandon

**Comment by fgnutzi** [comment]
I can confirm that Side Transition works now as intendened.
But there are 2 fields for the Transition Speed. One in the Printer Setup and one in the style Settings. I haven´t tried which one is been used but they do not update each other. Thats confusing.

Greetings Frank

**Comment by brandonbloch** [comment]
Hi Frank,

I'm not sure which two fields you're referring to. The printer setup options relate to non-changing physical aspects of your printer, i.e. whether it can side transition in place or requires a jogging motion, and the physical location to do the transition. In contrast, the print-specific options like purge speed are found in the style settings.

If you're referring to the fact that the selected style profile is copied onto your project, you can update the linked style profile or revert to it using the buttons on the Settings step. The buttons will be greyed out if there are no differences between the two:

<img width="810" alt="screen shot 2019-02-19 at 7 50 38 am" src="https://user-images.githubusercontent.com/217964/53016213-1144e580-341b-11e9-8a1e-4728a7f46bbb.png">

**Comment by fgnutzi** [comment]
Hello Brandon,
yes, you are right!
Thank you.

Greetings
Frank
