### ISSUE TITLE
Support Block/Enforcement

### ISSUE THREAD

**Issue by dbsweeny** [MosaicManufacturing/canvas-issues#81]
I would find it useful (as I imagine other users would, too) to be able to either enforce and/or block supports being autogenerated in specific locations on a model. I'll spare you too much description of what I mean as this is a common feature on other slicing software, so I'm sure you're aware of the functions of the feature, but Canvas often generates supports where I understand they technically should be, but where I know from experience they are not actually needed, so I would like to be able to block some, but not all, supports in order to speed up a print and reduce its waste. Super useful.

**Comment by bil-bas** [comment]
Usually there is a "only supports touching bed" and "supports everywhere" option (well, in Cura there is :D)

**Comment by dbsweeny** [comment]
An example from Slic3rPE of a custom shape (the green cube) that can be set as either a support enforcer or support blocker. This is the sort of thing I had in mind.

![screen shot 2019-02-23 at 2 04 31 pm](https://user-images.githubusercontent.com/43355368/53290588-29e33180-3774-11e9-901a-5e231f1871d6.png)

**Comment by bil-bas** [comment]
Ah sorry, that is clear now (and obviously useful!)

**Comment by brandonbloch** [comment]
Hi all,

This feature is finally here! With the new support painting UI, you can manually designate areas for support, starting from a blank slate or an automatic fill that can do a "from bed only" style fill!

Cheers,
Brandon
