### ISSUE TITLE
Firmware retractions are not generated

### ISSUE THREAD

**Issue by cmroche** [MosaicManufacturing/canvas-issues#92]
**Describe the bug**

Using a printer configured to use "firmware retractions" any design using a profile associated with this printer will either generate standard retractions in the gcode (when retractions are turned on) or none at all.

This is what I am seeing in the gcode output

```
; extruder(s) off
M103
;
; 'Destring/Wipe/Jump Path', 0.0 [feed mm/s], 20.0 [head mm/s]
; 'Destring Suck'
G1 E-2 F2400
; head speed 20.000000, filament speed 0.000000, preload 0.000000
; Perimeter Length = 143.024109
;
; 'Perimeter Path', 0.6 [feed mm/s], 20.0 [head mm/s]
G1 X158.344 Y119.73 E0 F9000
; 'Destring Prime'
G1 E2 F2400
; extruder on
M101
```

When I am expecting only to see `G10` for retract, and `G11` for recover.

See screenshots for config.

**To Reproduce**
1. Create a new printer profile, with 5D relative and "enable firmware retractions"
2. Create a new profile with retractions enabled, any retraction settings
3. Create a new project using this profile
4. Import and model, click on "Preview"
5. Click on "Download GCODE"
6. Open GCODE in text editor and search for `G10` or `G11` (they will not be found)
7. Search for `E-2` in the GCODE and you will find standard retractions

**Expected behavior**
All retractions are generated with a `G10` command, and recoveries with `G11`. This applies to both Marlin and Reprapfirmware

https://duet3d.dozuki.com/Wiki/Gcode
http://marlinfw.org/meta/gcode/

**Screenshots**

Printer config
![image](https://user-images.githubusercontent.com/1007595/53685006-e5f7ab80-3ce2-11e9-85e7-2a346a0b53a3.png)

Profile Settings
![image](https://user-images.githubusercontent.com/1007595/53685009-f1e36d80-3ce2-11e9-943d-b0e89e43387a.png)

**Operating System (please complete the following information):**
 - OS: OSX 10.14.3
 - Browser Chrome and Safari
 - Version Latest (sorry not clear on precise number, but likely not relevant)

**Additional context**

I'm using a Duet Maestro, with Canvas hub to print with a 600mm bowden tube. My filament configurations carry carefully tuned profiles for retractions and pressure advance functionality per material type and material brand.

Firmware retractions allow adjustments on the fly, without reslicing, but more importantly software retractions seem to interfere with larger pressure advance values in RRF and produce lower quality results when using equivalent settings compared with firmware retractions in my experience.

**Comment by brandonbloch** [comment]
HI @cmroche,

Thanks for reporting this issue to us! It seems the value of this setting was being passed into the slicer incorrectly. It has now been fixed and you should see the G10/G11 commands instead of retractions. Let us know if you still notice any funkiness around this functionality.

Cheers,
Brandon
