### ISSUE TITLE
Incorrect rendering of specific STL files (no lighting)

### ISSUE THREAD

**Issue by bil-bas** [MosaicManufacturing/canvas-issues#96]
**Describe the bug**
Rendering of specific stls shows them without any lighting. I'm guessing there are no normals in the stl, but shouldn't you guess at them? STL viewer show the object properly.

**To Reproduce**
Load any of the stls in
[7_Wonders_+_Expansions_storage_solution_.zip](https://github.com/MosaicManufacturing/canvas-issues/files/2988077/7_Wonders_%2B_Expansions_storage_solution_.zip)
(from [thingiverse](https://www.thingiverse.com/thing:3293262))

**Expected behavior**
Should show the model lit up so you can see the geometry properly.

**Screenshots**
![Screenshot_20190320-122012](https://user-images.githubusercontent.com/159180/54683828-93075c00-4b0a-11e9-9a51-4280b4254d62.png)

![Screenshot_20190320-123239](https://user-images.githubusercontent.com/159180/54684482-5b99af00-4b0c-11e9-9e44-35f3cc93d495.png)

**Operating System (please complete the following information):**
 - OS: Android 8.1.0
 - Browser chrome

**Comment by bil-bas** [comment]
p.s. slicing seems to work correctly

**Comment by bil-bas** [comment]
Interestingly, importing the STL into tinkercad, making an alteration and then exporting, gave an STL that displayed propelry in CANVAS.

**Comment by brandonbloch** [comment]
Hi @Spooner,

Thanks for reporting this! TBH I can't believe it's taken this long for any of us to notice. The issue had to do with incorrect triangle normals in the STL, which would only affect visual preview (importing to Tinkercad and re-exporting probably caused the normals to regenerate). The issue has been fixed, and the correction is now live! Reloading the page, you should now see them being lit correctly.

Cheers,
Brandon
