### ISSUE TITLE
Transition Speed

### ISSUE THREAD

**Issue by Setesh82** [MosaicManufacturing/canvas-issues#98]
Allow the speed of the transition to be specified for the tower.  Right now you can only do this with the side transition option.  

This would prevent jams when transitioning between different types of filament such and rigid and flexible.  Right now the it isn't possible to have the rigid material print faster then the flexible needs to as it will jam when transitioning from flexible to rigid.

**Comment by brandonbloch** [comment]
This setting is now available in CANVAS, in the Transition section under Transition Tower.
