### ISSUE TITLE
Can't change the splice settings of default PLA

### ISSUE THREAD

**Issue by CroXY3D** [MosaicManufacturing/canvas-issues#99]
And the defaults (0,0,0 it appears) are much too cold and always result in a splice that breaks. 

So, if I forget to change the material to PLA settings that actually work (2,2,2) then the print fails.  This has caused more failed prints than anything.

**Comment by brandonbloch** [comment]
This is by design (not being able to change the defaults), but we are planning to add a setting for choosing the default material to be used by new projects which should alleviate this issue.
